concrete_distances = {}
concrete_distances["transport-belt"]             = {search = 2, radius = 2}
concrete_distances["transport-belt-to-ground"]   = {search = 2, radius = 2}
concrete_distances["splitter"]                   = {search = 2, radius = 2}
concrete_distances["inserter"]                   = {search = 2, radius = 1}
concrete_distances["straight-rail"]              = {search = 4, radius = 3}
concrete_distances["curved-rail"]                = {search = 4, radius = 3}
concrete_distances["assembling-machine"]         = {search = 4, radius = 3}
concrete_distances["furnace"]                    = {search = 4, radius = 3}
concrete_distances["boiler"]                     = {search = 4, radius = 3}
concrete_distances["electric-pole"]              = {search = 4, radius = 2}
concrete_distances["container"]                  = {search = 2, radius = 1}
concrete_distances["logistic-container"]         = {search = 2, radius = 1}
concrete_distances["generator"]                  = {search = 2, radius = 2}
concrete_distances["pipe"]                       = {search = 2, radius = 1}
concrete_distances["pipe-to-ground"]             = {search = 2, radius = 1}
concrete_distances["pump"]                       = {search = 5, radius = 5}
concrete_distances["radar"]                      = {search = 4, radius = 3}
concrete_distances["lamp"]                       = {search = 4, radius = 2}
concrete_distances["wall"]                       = {search = 2, radius = 2}
concrete_distances["turret"]                     = {search = 2, radius = 2}
concrete_distances["train-stop"]                 = {search = 2, radius = 2}
concrete_distances["rail-signal"]                = {search = 2, radius = 2}
concrete_distances["rail-chain-signal"]          = {search = 2, radius = 2}
concrete_distances["lab"]                        = {search = 4, radius = 3}
concrete_distances["rocket-sile"]                = {search = 5, radius = 5}
concrete_distances["roboport"]                   = {search = 5, radius = 5}
concrete_distances["accumulator"]                = {search = 2, radius = 2}
concrete_distances["beacon"]                     = {search = 4, radius = 3}
